FIND_PATH(GLFW3_INCLUDE_DIR "GLFW/glfw3.h" PATHS "/usr/local/include" )
FIND_LIBRARY(GLFW3_LIBRARY NAMES glfw3 glfw PATHS "/usr/local/lib" )

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLFW3 DEFAULT_MSG GLFW3_LIBRARY GLFW3_INCLUDE_DIR)